import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import process from "node:process";
import { build } from "esbuild";

function parseOutdir(argv) {
  const index = argv.indexOf("--outdir");
  if (index === -1) return resolve("dist");
  const value = argv[index + 1];
  if (!value) throw new Error("--outdir requires a path");
  return resolve(value);
}

const outdir = parseOutdir(process.argv.slice(2));
await mkdir(outdir, { recursive: true });

const common = {
  bundle: true,
  platform: "node",
  target: "node24",
  sourcemap: false,
  minify: false,
  legalComments: "none",
  charset: "utf8",
  logLevel: "info",
  format: "cjs",
};

for (const [entry, filename] of [
  ["src/main.ts", "main.cjs"],
  ["src/engine.ts", "engine.cjs"],
]) {
  await build({
    ...common,
    entryPoints: [resolve(entry)],
    outfile: resolve(outdir, filename),
    banner: {
      js: `// Generated by scripts/build.mjs from ${entry}. Do not edit directly.`,
    },
  });
}
